export const medicinalUses = [
  "Bacterial Infections",
  "Viral Infections",
  "Fungal Infections",
  "Pain Relief",
  "Inflammation Reduction",
  "Fever Reduction",
  "Nausea and Vomiting Prevention",
  "Allergy Symptom Relief",
  "Bronchodilation",
  "Hypertension Control",
  "Anticoagulation",
  "Diabetes Management",
  "Depression Treatment",
  "Anxiety Management",
  "Mood Disorder Treatment",
  "Schizophrenia Treatment",
  "Bipolar Disorder Management",
  "Immunosuppression",
  "Hormone Replacement Therapy",
  "Diuretic Action",
  "Muscle Spasm Relief",
  "Cardiac Condition Treatment",
  "Organ Transplant Immunosuppression",
  "Hormonal Imbalance Management",
  "Blood Clot Prevention",
  "Autoimmune Disorder Treatment",
  "Urinary Conditions",
  "Skin Conditions (Topical Medications)",
  "Asthma Management",
  "Edema Treatment"
];